<a href="https://colab.research.google.com/github/sukeshnagaraja/snagar0/blob/master/00_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### references 
## https://www.tensorflow.org/guide/tensor
## https://www.tensorflow.org/api_docs/python/tf/constant
## 

##numpy study 
## https://numpy.org/doc/stable/user/basics.broadcasting.html
#https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html


In [18]:
#float32
# Notes
#1. The softmax function, also known as softargmax or normalized exponential function, converts a vector of K real numbers into a probability distribution of K possible outcomes. 
#   It is a generalization of the logistic function to multiple dimensions, and used in multinomial logistic regression.
# its used for multi class predictions, the outcome of softmax sums up to 1.0 

#logit is a non empty tensor 
# by defualt softmax uses -1 dimension ,last dimension , 

# tf.nn.softmax is same as tf.exp(logit)/tf.reduce_sum(tf.exp(logit)), its a formula 


# for more info refer 
# https://victorzhou.com/blog/softmax/

'''
Softmax turns arbitrary real values into probabilities, which are often useful in Machine Learning. The math behind it is pretty simple: given some numbers,

    Raise e (the mathematical constant) to the power of each of those numbers.
    Sum up all the exponentials (powers of eee). This result is the denominator.
    Use each number’s exponential as its numerator.
    Probability=NumeratorDenominator\text{Probability} = \frac{\text{Numerator}}{\text{Denominator}}Probability=DenominatorNumerator​.

Written more fancily, Softmax performs the following transform on nnn numbers x1…xnx_1 \ldots x_nx1​…xn​:
s(xi)=exi∑j=1nexjs(x_i) = \frac{e^{x_i}}{\sum_{j=1}^n e^{x_j}}s(xi​)=∑j=1n​exj​exi​​

The outputs of the Softmax transform are always in the range [0,1][0, 1][0,1] and add up to 1. Hence, they form a probability distribution.

'''


#why do we need softmax? say input= [-1,0,3,5], here i know 5,3,0,-1 is the order with highest numbers, to tell this
# probabilistically meaning with % of confidence we use softmax and tell [0.0021657 , 0.00588697, 0.11824302, 0.8737043 ] 
#the same with confidence level

#Softmax answer the classification questions with probabilities, 
#which are more useful than simpler answers (e.g. binary yes/no).



'\nSoftmax turns arbitrary real values into probabilities, which are often useful in Machine Learning. The math behind it is pretty simple: given some numbers,\n\n    Raise e (the mathematical constant) to the power of each of those numbers.\n    Sum up all the exponentials (powers of eee). This result is the denominator.\n    Use each number’s exponential as its numerator.\n    Probability=NumeratorDenominator\text{Probability} = \x0crac{\text{Numerator}}{\text{Denominator}}Probability=DenominatorNumerator\u200b.\n\nWritten more fancily, Softmax performs the following transform on nnn numbers x1…xnx_1 \\ldots x_nx1\u200b…xn\u200b:\ns(xi)=exi∑j=1nexjs(x_i) = \x0crac{e^{x_i}}{\\sum_{j=1}^n e^{x_j}}s(xi\u200b)=∑j=1n\u200bexj\u200bexi\u200b\u200b\n\nThe outputs of the Softmax transform are always in the range [0,1][0, 1][0,1] and add up to 1. Hence, they form a probability distribution.\n\n'

In [1]:
import tensorflow  as tf

In [20]:
t1=tf.constant([-1.0,0.0,3.0,5.0])
tf.nn.softmax(t1)


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.0021657 , 0.00588697, 0.11824302, 0.8737043 ], dtype=float32)>

In [8]:
#scalar values has 0 dimension
val=tf.constant(1)
val,val.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, 0)

In [7]:
#list of values - 1 dimension
val=tf.constant([1,2,3,4])
val,val.ndim

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 1)

In [9]:
#list of lists - 2dimensions
val=tf.constant([[1,2,3],[4,5,6]])
val,val.ndim  


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, 2)

In [10]:
val=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[0,8],[0,7]]])

ValueError: ignored

In [12]:
#list of list iof lists - 3dimensions
val=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[0,8,0],[0,7,0]]])
val,val.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[ 0,  8,  0],
         [ 0,  7,  0]]], dtype=int32)>, 3)

In [14]:
val=tf.constant([1,2,3,4],shape=(2,2))
val

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
val=tf.constant([1,2,3,4],shape=(2,3))
val

TypeError: ignored

In [21]:
# if a constant is a list then its length must be less than or equal to shape
val=tf.constant([1,2,3,4,5,6],shape=(3,2))
val,val.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, 2)

In [ ]:
# matrix is 2 dimensional
# scalar is zero dimensional
# tensors are n dimensional

In [22]:
from numpy import float16
val=tf.constant([1,2,3,4,5,6],shape=(3,2),dtype=float16)
val,val.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float16)>, 2)

In [25]:
tf.dtypes.DType

tensorflow.python.framework.dtypes.DType

In [29]:
val=val+val
val

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  8.],
       [12., 16.],
       [20., 24.]], dtype=float16)>

In [30]:
val

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  8.],
       [12., 16.],
       [20., 24.]], dtype=float16)>

In [31]:
import numpy as np

In [32]:
np.array(val)

array([[ 4.,  8.],
       [12., 16.],
       [20., 24.]], dtype=float16)

In [33]:
val.numpy()

array([[ 4.,  8.],
       [12., 16.],
       [20., 24.]], dtype=float16)

In [34]:
# Ragged Tensors 
# https://www.tensorflow.org/guide/tensor#ragged_tensors


In [ ]:
# sparse tensors 

In [4]:
val=tf.constant([[1.0,2.1,3.2],[10.0,9.1,12.89]]) #matrix 
val

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.  ,  2.1 ,  3.2 ],
       [10.  ,  9.1 , 12.89]], dtype=float32)>

In [6]:
tf.math.argmax(val) #default axis is 0, which is column wise 

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1])>

In [7]:
tf.math.argmax(val,1)  #axis 1 is row wise , finds the largest value index in vector/matrix or any dimension

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [10]:
val0=tf.constant([1.0,2.1,3.2]) #vector 
tf.math.argmin(val0)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [11]:
tf.reduce_max(val0) #this function will find largest value not its index 

<tf.Tensor: shape=(), dtype=float32, numpy=3.2>

In [12]:
tf.reduce_min(val) #for info about function duouble click on function 

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [13]:
tf.nn.softmax(val0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.0767508 , 0.23057215, 0.6926771 ], dtype=float32)>

In [21]:
## indexing 

rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())


[ 0  1  1  2  3  5  8 13 21 34]


In [22]:
rank_1_tensor[:].numpy()  #indexing with slices keep the axis

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)

In [23]:
rank_1_tensor[0].numpy() #indexing with scalar removes the axis

0

In [25]:
from tensorflow.python.ops.gen_array_ops import rank
rank_1_tensor[:4].numpy()     
rank_1_tensor[::-1].numpy() #to reverse the tensor 

array([34, 21, 13,  8,  5,  3,  2,  1,  1,  0], dtype=int32)

In [ ]:
#shape of a tensor 
# batch axis, height,width ,features 

# heigth & width are called spatial dimensions


#terminology 

#1. shape : the length of each axis (row axis1 /column axis0) of a tensor
#2. rank : number of tensor axes 
#3. axis or dimension : particular dimension of a tensor 
# size - number of elements in the tensor 
#Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
#Axis or Dimension: A particular dimension of a tensor.
#Size: The total number of items in the tensor, the product of the shape vector's elements.   

In [26]:
# single indexing
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())


Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [28]:
#Multi-axis indexing

#Higher rank tensors are indexed by passing multiple indices.

#The exact same rules as in the single-axis case apply to each axis independently.

rank_2_tensor= tf.constant([[1.,2.],
 [3.,4.],
 [5.,6.]])

In [29]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")


Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [ ]:
# refer tensor slicing guide 
# https://www.tensorflow.org/guide/tensor_slicing


In [34]:
#manipulating shapes

# we can use reshape , the only reason to use this is to combine or split adjacent axis 
# we cannot use reshape to swap axes for that use tf.transpose 


t3= tf.constant([[[ 0,1,2,3,4],
  [ 5,6,7,8,9]],
  [[10,11,12,13,14],
  [15,16,17,18,19]],
  [[20,21,22,23,24],
  [25,26,27,28,29]]])
t3

#For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

In [35]:
t3.ndim

3

In [36]:
tf.reshape(t3,[-1]) #flatten it out 

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

In [37]:
tf.reshape(t3,[3*2,5])

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]], dtype=int32)>

In [38]:
tf.reshape(t3,[3,2*5])

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)>

In [39]:
#Note

#Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.

#Swapping axes in tf.reshape does not work; you need tf.transpose for that.

# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(t3, [2, 3, 5]), "\n") 

# This is a mess
print(tf.reshape(t3, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(t3, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


In [ ]:
## more on Dtypes

'''
TensorFlow converts Python integers to tf.int32 and Python floating point numbers to tf.float32. 
Otherwise TensorFlow uses the same rules NumPy uses when converting to arrays.
'''

In [40]:
data=tf.constant([1,2,3,4,5],dtype=tf.float16)
data

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>

In [42]:
#convert float to int using cast function 
tf.cast(data,dtype=tf.uint16)

<tf.Tensor: shape=(5,), dtype=uint16, numpy=array([1, 2, 3, 4, 5], dtype=uint16)>

In [43]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)


tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


In [ ]:
#Broadcasting : 
#1. the smaller array is “broadcast” across the larger array so that they have compatible shapes.
#2. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 
#3.  In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

In [45]:
# These are the same computations
x = tf.constant([1, 2, 3]) #shape 1,3
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y)) #broadcasting, refer a diagram https://www.tensorflow.org/guide/tensor


tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [46]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading


tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [47]:
#Most of the time, broadcasting is both time and space efficient, as the broadcast operation 
#never materializes (to come into existence or become real) the expanded tensors in memory.

#You see what broadcasting looks like using tf.broadcast_to - this will materialize the tensor , 
# its not helpful in saving memory
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))


tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [ ]:
## tf.register_tensor_conversion_function 

#object classes like NumPy's ndarray, TensorShape, Python lists, and tf.Variable will all convert automatically.



In [48]:
# ragged tensors 

#a tensor with variable number of elements along some axis called ragged. 

#examples:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]


In [49]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")


ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [50]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)


<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [51]:
#The shape of a tf.RaggedTensor will contain some axes with unknown lengths:

print(ragged_tensor.shape)


(4, None)


In [ ]:
## string tensors 
## https://www.tensorflow.org/api_docs/python/tf/strings
## how to represent unicode strings in tensorflow https://www.tensorflow.org/text/guide/unicode


#The basic TensorFlow tf.string dtype allows you to build tensors of byte strings. Unicode strings are utf-8 encoded by default.

#If you use Python to construct strings, note that string literals are Unicode-encoded by default.

#A tf.string tensor treats byte strings as atomic units. This enables it to store byte strings of varying lengths. The string length is not included in the tensor dimensions.

In [52]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)


tf.Tensor(b'Gray wolf', shape=(), dtype=string)


In [54]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)


tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


In [55]:
tf.constant("🥳👍")
 #If you pass unicode characters they are utf-8 encoded

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

In [56]:
tf.strings.split(scalar_string_tensor,sep=' ')

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Gray', b'wolf'], dtype=object)>

In [57]:
# ...but it turns into a `RaggedTensor` if you split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(tensor_of_strings)) #it splits each eleemnts in a list based on a default separator space

#refer https://www.tensorflow.org/guide/tensor to visualize 


<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


In [58]:
# convert string representation of number to number 
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))


tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [ ]:
#Although you can't use tf.cast to turn a string tensor into numbers, you can convert it into bytes, and then into numbers.

#convert string to byte string 
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))

#convert string to number 
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)

print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)


#use tf.strings to manipulate strings 

In [59]:
# Or split it up as unicode and then decode it
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)



Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


In [ ]:
# The tf.string dtype is used for all raw bytes data in TensorFlow. 

## tf.io module 

# The tf.io module contains functions for converting data to and from bytes, including decoding images and parsing csv.

In [ ]:
# sparse tensors 
# Sparse tensors
# Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports tf.sparse.SparseTensor and related operations to store sparse data efficiently.

In [60]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [1]:

## variables - tensorflow variables is a recommended way to represent shared,persistent state your program manipulates. 
# Uncomment to see where your variables get placed (see below)
tf.debugging.set_log_device_placement(True)



NameError: ignored